import Head from "next/head"

import styles from "./Home.module.scss"

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>HOLA</h1>
    </div>
  )
}
export default Home
